### ISSUE TITLE
"Segmentation fault" when consulting files which contain shebang

### ISSUE THREAD

**Issue by dram** [infradig/trealla#1]
Trealla will exit with "Segmentation fault" when consulting files contain shebang, e.g.:

```
#!/usr/bin/env prolog

main :- write('Hello, world!'), nl.
```

**Comment by infradig** [comment]
Thanks. This is only a temporary repo but I will certainly fix that.

**Comment by dram** [comment]
Thanks.

Btw, I found that text in [LICENSE](https://github.com/infradig/trealla/blob/master/LICENSE) file is more like [ISC License](https://opensource.org/licenses/ISC) (with small difference), instead of [BSD 2-Clause License](https://opensource.org/licenses/BSD-2-Clause), which is mentioned in [README.md #L25](https://github.com/infradig/trealla/blame/master/README.md#L25).

I'm not a lawyer, and not familiar with those licenses, just want to point this inconsistency.

**Comment by infradig** [comment]
Correct, I had originally BSD 2-clause but then copied the license file from an old project, which was ISC. This is my preferred license. I have corrected the README.

Thanks.

**Comment by infradig** [comment]
BTW, this project will be moving to https://github.com/trealla-lang/trealla soon.

**Comment by dram** [comment]
Cool!

Before it is moved, which place is preferred when reporting issues?

Just found another problem, I think `make OPT=-std=c11` in README should be `make OPT=-std=gnu11`, as I failed to compile with `-std=c11` using GCC 5.2.1.

**Comment by infradig** [comment]
I'll put in a note. But both GCC 4.9 and 5.4 accept -std=c11

**Comment by dram** [comment]
Not sure if I did something wrong, but when I compile Trealla with `-std=c11`, several errors and many warnings are printed, I think they are caused by feature test macros, following some of them.

```
src/trealla.c: In function ‘dict’:
src/trealla.c:246:10: warning: implicit declaration of function ‘strdup’ [-Wimplicit-function-declaration]
  value = strdup(key);
          ^
```

It is similar to this [SO question](http://stackoverflow.com/questions/19641460/using-strdup-in-c11).

```
src/bifs_sys.c: In function ‘bif_sys_exists_file1’:
src/bifs_sys.c:109:20: error: ‘S_IFMT’ undeclared (first use in this function)
  if ((st.st_mode & S_IFMT) != S_IFREG) return 0;
                    ^
```

This one is similar to this [SO question](http://stackoverflow.com/questions/28547271/s-ifmt-and-s-ifreg-undefined-with-std-c11-or-std-gnu11).

```
src/bifs_sys.c: In function ‘bif_sys_hsleep1’:
src/bifs_sys.c:23:20: warning: implicit declaration of function ‘usleep’ [-Wimplicit-function-declaration]
 #define msleep(ms) usleep((ms)*1000)
                    ^
```

`usleep` seems to be deprecated, `nanosleep` is recommended, according to the [man page](https://linux.die.net/man/3/usleep).

```
src/network.c: In function ‘join_multicast4’:
src/network.c:2135:18: error: storage size of ‘mreq’ isn’t known
   struct ip_mreq mreq;
                  ^
src/network.c:2135:18: warning: unused variable ‘mreq’ [-Wunused-variable]
```

When looking into `netinet/in.h`, `struct ip_mreq` is guarded by `__USE_MISC` or `__USE_GNU`, not sure the reason behind.

**Comment by infradig** [comment]
Using _DEFAULT_SOURCE is supposed to handle all that. Try _GNU_SOURCE or
_BSD_SOURCE (which is what all my old projects used to use).

  make 'OPT=-std=c11 -D_BSD_SOURCE'

By the way what distro are you using? I am using Ubuntu 16.04 mostly, plus
some FreeBSD 10.3 now and then.

**Comment by dram** [comment]
I use both Debian and CentOS heavily.

I think I find the problem, `_DEFAULT_SOURCE` is introduced in glibc 2.19, while it is 2.17 in CentOS 7.
